# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('name', models.CharField(default='username', max_length=30)),
                ('mid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('is_block', models.BooleanField(default=False)),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='上次修改時間')),
            ],
        ),
    ]
