# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=90)),
                ('friend_id', models.CharField(max_length=40)),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='上次修改時間')),
            ],
        ),
    ]
