language: python
python:
- '3.5'
install: pip install -r requirements.txt
script:
- bash test_travis.sh
deploy:
  provider: heroku
  api_key:
    secure: ikgJtiEoSl24W+jIzbuLBFVQ9CceO8boCtt/tjEjQ1JKUzZnm44MPN4+rqsuLEIgPCDho5ZT62+ysQzlQeZ26LUWXI5NtbKUwxtbgheBNI7BeYprPlqgrn9jW+60bPb5pr68eVlzcCbCl7JdbsZacHObmIiWm2iZIDvIL1A61IsUX4v9aD1ImdO2ixgxqv3o/0K1cCgT6RBNb7tql42akdUTALvLCkrgz3Mg20pdZt88A1hthbDE23a4PYMXm8g806pO/ZQJpc9MSnamGN6J1QpQJwwpmODD7Ur4ep5MG8umZR5no41zr4nOpYrRo+1yI99xu9H+o3L9mDFJ2KicS/KyKifUXhV0hGqaTSSb+akq6WRCNmRtVnLTe0cMCxtjmNco8wfj43f9yVWN3tKKbqwUe3wi4aU2xh3JkLT5uUADqX2bY4HBlxg9CxvY9LzsAC+EoF5lz2Z5Cog36CmAfYoBwmxEA07bv1CEa84SIChiWbIcdfyPhs1Kko/w7K5m5Q6+qEgFEqATJCqWmLutgTlw+5JyAAKS1TNaP4suUubwUJ90r47c5jSojA19g8lB2XWuEPp87XKu/8m2PxM6Lw9yjbR9/aeDOMXNlgODrIZaH8Idx4VrAuL6BZ7Vhj69nSvXVDHP4Lbf1qOtTHA4cW7OZ4xpDu8Tw+SN6bXC7a0=
